- name: install RDO dépôt for OpenVswitch
  yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-juno/rdo-release-juno-1.noarch.rpm state=present

- name: install openvswitch
  yum: name=openvswitch state=present update_cache=yes

- name: configure bridge
  template: src=ifcfg-br.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ krast_bridge_name }} owner=root mode="u=rw,g=r,o=r"
